name: Configuration Split
type: module
description: Configuration filter for importing and exporting split config
core: 8.x
package: Config
configure: entity.config_split.collection
dependencies:
  - config_filter:config_filter
